### PR TITLE
Remove double file extensions from HTML files

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Comment by goneall** [comment]
Fixed the RDFa license generator tool to not add the extra .html extensions.  Updated files have been pushed to the git repo.

**Comment by sschuberth** [comment]
@goneall Also here, the old `.html.html` files are not gone from the repository.

**Comment by goneall** [comment]
@sschuberth Quite curious - on my local git repo, the files are not there.  I'll try committing a delete to all files then commit a new set of files and see if that clears it up.

**Comment by goneall** [comment]
@sschuberth My bad - forgot to add the switch on git add to remove the files

**Comment by goneall** [comment]
@sschuberth New push on it's way

**Comment by sschuberth** [comment]
@goneall Sorry, I still see `.html.html` files listed at https://github.com/spdx/license-list-data/tree/master/html

**Comment by goneall** [comment]
@sschuberth thanks for checking - looks like I missed the exceptions

**Comment by goneall** [comment]
@sschuberth I just pushed another updated .html directory.  Fixed the exceptions (which were missing the .html endings) and the deprecated licenses (which had 2 .html endings).  I did take the time to check the directory this time - so hopefully everything is OK.

**Comment by sschuberth** [comment]
@goneall I think the `html` and `json` directories are looking good now. However, I believe there are some remaining issues. I'll file them here at the GitHub tracker.

**Pull request closed without merging**
