### PR TITLE
Update CC-BY-NC-ND-2.0.txt

### PR DESCRIPTION
**Pull request by seydel1847**
Fixed 'Performance Royalties Under Blanket Licenses'.

### CODE REVIEW

**Comment by seabass-labrax** [comment]
Welcome, @seydel1847, and thank you for your interest in improving the SPDX License List! :)

As the contents of this repository are automatically generated from the [license-list-XML](https://github.com/spdx/license-list-XML/) repository, your fixes would unfortunately get overwritten when we release version 3.14 of the list later this month.

Would you be able to send a pull request to the license-list-XML repository, please? The two files that would need to be modified are the license's XML file in `src/` and assocatiated text file in `test/simpleTestForGenerator/` (which is used as part of the automated testing system).

**Review by Elpasto28 — APPROVED** [review]

**Comment by seabass-labrax** [comment]
Hello @Elpasto28! I noticed you reviewed this pull request; welcome to SPDX! If you'd like to be involved with SPDX on into the future, you might want to consider joining our Tech or Legal team calls (on Zoom and Jitsi respectively). Does that sound like your sort of thing?  Looking forward to your response!

**Comment by Elpasto28** [comment]
> ¡Hola @ Elpasto28 ! Noté que revisaste esta solicitud de extracción; ¡bienvenido a SPDX! Si desea participar con SPDX en el futuro, es posible que desee considerar unirse a las llamadas de nuestro equipo técnico o legal (en Zoom y Jitsi, respectivamente). ¿Suena eso como tu tipo de cosas? ¡Esperamos su respuesta!

#me encantaría participar y gracias

**Review by Elpasto28 — APPROVED** [review]

**Review by Elpasto28 — APPROVED** [review]

**Review by Elpasto28 — APPROVED** [review]

**Comment by seabass-labrax** [comment]
> #me encantaría participar y gracias

That's great, @Elpasto28! Our next Tech Team meeting is on Tuesday; all the details are [on our wiki](https://wiki.spdx.org/view/Technical_Team). Please note that the meeting is held in English though.

**Comment by swinslow** [comment]
This was fixed by https://github.com/spdx/license-list-XML/pull/1318 and will be updated on the SPDX License List website in the 3.15 release. Thanks all!

**Pull request closed without merging**
